import type { AgentRun } from "../../domain/agent-run/schema";
import type { EmergencyState } from "../../domain/emergency-state/schema";
import type { StateChange } from "../../domain/state-change/schema";

const timestamp = "2026-10-02T08:46:18.000Z";

const initialState: EmergencyState = {
  incident: {
    id: "INC-2026-001",
    title: "Urban high-rise fire",
    description: "Fire reported in a central district high-rise.",
    type: "FIRE",
    status: "ACTIVE",
    severity: "CRITICAL",
    priority: "URGENT",
    location: {
      latitude: 18.5204,
      longitude: 73.8567,
      address: "Central district, Building 14",
    },
    affectedPopulation: 35,
    hazards: ["Smoke", "Structural fire"],
    reportedAt: "2026-10-02T08:38:00.000Z",
    updatedAt: timestamp,
  },
  resources: [
    {
      id: "RES-RT-01",
      name: "Rescue Team Alpha",
      type: "RESCUE_TEAM",
      status: "AVAILABLE",
      location: { latitude: 18.524, longitude: 73.851 },
      capacity: 8,
      currentAssignmentId: null,
      capabilities: ["Urban rescue"],
      updatedAt: timestamp,
    },
    {
      id: "RES-RT-02",
      name: "Rescue Team Bravo",
      type: "RESCUE_TEAM",
      status: "AVAILABLE",
      location: { latitude: 18.517, longitude: 73.861 },
      capacity: 8,
      currentAssignmentId: null,
      capabilities: ["Urban rescue"],
      updatedAt: timestamp,
    },
    {
      id: "RES-AMB-01",
      name: "Ambulance 07",
      type: "AMBULANCE",
      status: "AVAILABLE",
      location: { latitude: 18.515, longitude: 73.849 },
      capacity: 4,
      currentAssignmentId: null,
      capabilities: ["Patient transport"],
      updatedAt: timestamp,
    },
    {
      id: "RES-AMB-02",
      name: "Ambulance 08",
      type: "AMBULANCE",
      status: "AVAILABLE",
      location: { latitude: 18.526, longitude: 73.863 },
      capacity: 4,
      currentAssignmentId: null,
      capabilities: ["Patient transport"],
      updatedAt: timestamp,
    },
    {
      id: "RES-AMB-03",
      name: "Ambulance 09",
      type: "AMBULANCE",
      status: "AVAILABLE",
      location: { latitude: 18.512, longitude: 73.857 },
      capacity: 4,
      currentAssignmentId: null,
      capabilities: ["Patient transport"],
      updatedAt: timestamp,
    },
  ],
  facilities: [
    {
      id: "FAC-HOSP-A",
      name: "Hospital A",
      type: "HOSPITAL",
      status: "OPERATIONAL",
      location: { latitude: 18.534, longitude: 73.868, address: "North medical district" },
      totalCapacity: 20,
      availableCapacity: 20,
      capabilities: ["Emergency care"],
      updatedAt: timestamp,
    },
    {
      id: "FAC-HOSP-B",
      name: "Hospital B",
      type: "HOSPITAL",
      status: "LIMITED",
      location: { latitude: 18.505, longitude: 73.847, address: "South medical district" },
      totalCapacity: 10,
      availableCapacity: 10,
      capabilities: ["Emergency care"],
      updatedAt: timestamp,
    },
  ],
  routes: [
    {
      id: "R1",
      name: "Primary access route",
      status: "OPEN",
      distanceKm: 3.2,
      estimatedTravelMinutes: 9,
      origin: { latitude: 18.515, longitude: 73.849 },
      destination: { latitude: 18.5204, longitude: 73.8567 },
      blockedReason: null,
      updatedAt: timestamp,
    },
    {
      id: "R2",
      name: "North alternative",
      status: "OPEN",
      distanceKm: 4.1,
      estimatedTravelMinutes: 12,
      origin: { latitude: 18.534, longitude: 73.868 },
      destination: { latitude: 18.5204, longitude: 73.8567 },
      blockedReason: null,
      updatedAt: timestamp,
    },
    {
      id: "R3",
      name: "South access route",
      status: "OPEN",
      distanceKm: 4.8,
      estimatedTravelMinutes: 14,
      origin: { latitude: 18.505, longitude: 73.847 },
      destination: { latitude: 18.5204, longitude: 73.8567 },
      blockedReason: null,
      updatedAt: timestamp,
    },
  ],
  planActions: [
    {
      id: "ACT-001",
      planId: "PLAN-001",
      sequence: 1,
      type: "DISPATCH_RESOURCE",
      status: "PENDING",
      description: "Dispatch Rescue Team Alpha",
      priority: "URGENT",
      resourceIds: ["RES-RT-01"],
      facilityIds: [],
      routeIds: ["R1"],
      targetLocation: { latitude: 18.5204, longitude: 73.8567 },
      estimatedDurationMinutes: 8,
      createdAt: "2026-10-02T08:41:00.000Z",
      updatedAt: "2026-10-02T08:41:00.000Z",
    },
    {
      id: "ACT-002",
      planId: "PLAN-001",
      sequence: 2,
      type: "TRANSPORT_PEOPLE",
      status: "PENDING",
      description: "Route ambulance via R1",
      priority: "URGENT",
      resourceIds: ["RES-AMB-01"],
      facilityIds: [],
      routeIds: ["R1"],
      capacityDemand: null,
      targetLocation: { latitude: 18.5204, longitude: 73.8567 },
      estimatedDurationMinutes: 9,
      createdAt: "2026-10-02T08:41:00.000Z",
      updatedAt: "2026-10-02T08:41:00.000Z",
    },
    {
      id: "ACT-003",
      planId: "PLAN-001",
      sequence: 3,
      type: "NOTIFY_FACILITY",
      status: "PENDING",
      description: "Allocate 12 patients to Hospital A",
      priority: "HIGH",
      resourceIds: [],
      facilityIds: ["FAC-HOSP-A"],
      routeIds: [],
      capacityDemand: 12,
      targetLocation: null,
      estimatedDurationMinutes: 5,
      createdAt: "2026-10-02T08:41:00.000Z",
      updatedAt: "2026-10-02T08:41:00.000Z",
    },
    {
      id: "ACT-004",
      planId: "PLAN-001",
      sequence: 4,
      type: "NOTIFY_FACILITY",
      status: "PENDING",
      description: "Allocate remaining patients to Hospital B",
      priority: "HIGH",
      resourceIds: [],
      facilityIds: ["FAC-HOSP-B"],
      routeIds: [],
      capacityDemand: 8,
      targetLocation: null,
      estimatedDurationMinutes: 5,
      createdAt: "2026-10-02T08:41:00.000Z",
      updatedAt: "2026-10-02T08:41:00.000Z",
    },
  ],
  activePlan: {
    id: "PLAN-001",
    incidentId: "INC-2026-001",
    stateVersion: 12,
    status: "PENDING_APPROVAL",
    priority: "URGENT",
    summary: "Coordinate rescue access and hospital allocation.",
    rationale: "Prioritize the incident location and available emergency capacity.",
    generatedAt: "2026-10-02T08:41:00.000Z",
    updatedAt: "2026-10-02T08:41:00.000Z",
    actions: [
      { actionId: "ACT-001", sequence: 1 },
      { actionId: "ACT-002", sequence: 2 },
      { actionId: "ACT-003", sequence: 3 },
      { actionId: "ACT-004", sequence: 4 },
    ],
    alternatives: [],
    dependencies: {
      resourceIds: ["RES-RT-01", "RES-AMB-01"],
      facilityIds: ["FAC-HOSP-A", "FAC-HOSP-B"],
      routeIds: ["R1"],
    },
  },
  stateVersion: 12,
  updatedAt: timestamp,
};

const replannedState: EmergencyState = {
  ...initialState,
  planActions: initialState.planActions.map((action) =>
    action.id === "ACT-001" || action.id === "ACT-002"
      ? { ...action, planId: "PLAN-002", routeIds: ["R2"] }
      : { ...action, planId: "PLAN-002" },
  ),
  routes: initialState.routes.map((route) =>
    route.id === "R1"
      ? { ...route, status: "BLOCKED", blockedReason: "Flooding reported on primary access route." }
      : route,
  ),
  activePlan: {
    ...initialState.activePlan!,
    id: "PLAN-002",
    stateVersion: 13,
    status: "PENDING_APPROVAL",
    summary: "Re-route emergency access through R2.",
    generatedAt: "2026-10-02T08:46:12.000Z",
    updatedAt: "2026-10-02T08:46:12.000Z",
    actions: initialState.activePlan!.actions.map((action) =>
      action.actionId === "ACT-002" ? { ...action, sequence: 2 } : action,
    ),
    dependencies: {
      ...initialState.activePlan!.dependencies,
      routeIds: ["R2"],
    },
  },
  stateVersion: 13,
  updatedAt: "2026-10-02T08:46:18.000Z",
};

const agentRuns: readonly AgentRun[] = [
  {
    id: "RUN-RISK-001",
    incidentId: "INC-2026-001",
    agentType: "RISK_ASSESSMENT",
    status: "COMPLETED",
    stateVersion: 12,
    startedAt: "2026-10-02T08:40:20.000Z",
    completedAt: "2026-10-02T08:40:21.000Z",
    durationMs: 1000,
    output: { severity: "CRITICAL" },
    errorMessage: null,
  },
  {
    id: "RUN-ROUTE-001",
    incidentId: "INC-2026-001",
    agentType: "RESOURCE_ROUTING",
    status: "COMPLETED",
    stateVersion: 12,
    startedAt: "2026-10-02T08:40:23.000Z",
    completedAt: "2026-10-02T08:40:24.000Z",
    durationMs: 1000,
    output: { routes: ["R1", "R2"] },
    errorMessage: null,
  },
  {
    id: "RUN-PLAN-001",
    incidentId: "INC-2026-001",
    agentType: "RESPONSE_PLANNING",
    status: "COMPLETED",
    stateVersion: 13,
    startedAt: "2026-10-02T08:46:10.000Z",
    completedAt: "2026-10-02T08:46:12.000Z",
    durationMs: 2000,
    output: { planId: "PLAN-002" },
    errorMessage: null,
  },
];

const initialChanges: readonly StateChange[] = [
  {
    id: "CHANGE-001",
    entityType: "INCIDENT",
    entityId: "INC-2026-001",
    changeType: "CREATED",
    description: "Emergency detected",
    previousValue: null,
    newValue: "ACTIVE",
    occurredAt: "2026-10-02T08:38:00.000Z",
    detectedAt: "2026-10-02T08:38:00.000Z",
  },
  {
    id: "CHANGE-002",
    entityType: "PLAN",
    entityId: "PLAN-001",
    changeType: "CREATED",
    description: "Response plan generated",
    previousValue: null,
    newValue: "PENDING_APPROVAL",
    occurredAt: "2026-10-02T08:41:00.000Z",
    detectedAt: "2026-10-02T08:41:00.000Z",
  },
];

const replannedChanges: readonly StateChange[] = [
  ...initialChanges,
  {
    id: "CHANGE-003",
    entityType: "ROUTE",
    entityId: "R1",
    changeType: "STATUS_CHANGED",
    description: "Route R1 blocked",
    previousValue: "OPEN",
    newValue: "BLOCKED",
    occurredAt: "2026-10-02T08:45:00.000Z",
    detectedAt: "2026-10-02T08:45:00.000Z",
  },
  {
    id: "CHANGE-004",
    entityType: "PLAN",
    entityId: "PLAN-002",
    changeType: "CREATED",
    description: "Revised plan generated",
    previousValue: null,
    newValue: "PENDING_APPROVAL",
    occurredAt: "2026-10-02T08:46:12.000Z",
    detectedAt: "2026-10-02T08:46:12.000Z",
  },
];

export type DemoScenario = "initial" | "replanned";

export type DemoStateSnapshot = {
  state: EmergencyState;
  agentRuns: readonly AgentRun[];
  stateChanges: readonly StateChange[];
};

export function getDemoState(scenario: DemoScenario): DemoStateSnapshot {
  return {
    state: scenario === "initial" ? initialState : replannedState,
    agentRuns,
    stateChanges: scenario === "initial" ? initialChanges : replannedChanges,
  };
}
